name: Build Fractal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Clean build folder
      run: ./gradlew clean

    - name: Execute Fractal build
      run: ./gradlew build

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: beta
        files: build/libs/Fractal*.jar
